dist: xenial
language: node_js
node_js:
- '10'
- '14'
script:
- make
after_success:
- make report-coverage
deploy:
  on: 
    tags: true
    node_js: '10'
  provider: npm
  tag: next
  email: dmuino@gmail.com
  api_key:
    secure: q4imDe+IdQz+XqvbC1vXcxTuFf1DYJI3XsZ2o33FIIEFomzLDFole7+jGA8NfyQbAqOBOUxnSYDxa29NOoIJazGxr06wqEjyK6hA7ofq6UucbJ09u9IV8PLnJih2mW3b03lBUt6K3rg7ejP6T42kjd8vw4l73dBxBORsdQKNO7B4R0MSDdR7lfcFAe0wyi0N8dnwFRS9hbgz5yLMEH5y9tbMgBI6HRTVdKb80Sfa/8rD3wiEl+Fx6rnGpu7n241CtmdrV1V+mdDZY3bhCkmF1Rdm+DYHWabUW78J6mMFhkJIGOgxdkVKtyZP4w95fcaaxF13V75jYKt5UoVyIPE3dzE6zYa2D447PQtUxPojQLJFWUG0pOIK/+rebpGnVnzSYMFvIHcG7jw85YDhv0ZMvkwGerktqfCXbmwV6xgPyijhn+7cHW0n2fDCsyWZ2UazDBfg9LOrU5hl2jiwXX9ehGzH1XAY02ILHde1+LFXvvIw0ZRpkvtijB8FIetoADyeS1CAHqDQEKo66Lk1k9Teor6j4Hv6FpHmsmj5ma1ox7NQWpth42x7N9Qk3PTDj9QaGT1zCUAsN/8XGhnioeCStlr+022JNwnL6LbhGZWeTT3SMb3xQ/UCaK1GNYS+o0CGWkKU5waJuWBq5MiSDbl5t6WtMe759N5IcOd1IsFGxm8=

