language: node_js
node_js:
  - "6"
  - "10"
script:
  - npm run cover
after_success:
  - npm run travis-deploy-once "bash <(curl -s https://codecov.io/bash) || echo 'Codecov did not collect coverage reports'"
