name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator-js' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Make
        run: make
