name: Snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator-js' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18", "20", "22"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Test with Coverage
        run: npm run test-with-coverage

      - name: Check Coverage
        run: npm run check-coverage

      - name: Lint
        run: npm run lint
